### ISSUE TITLE
[conda] Install on Python 3.11 seems to be broken

### ISSUE THREAD

**Issue by rphel** [conda-forge/nvidia-apex-feedstock#29]
### Description

Dependency resolution seems to be broken with conda and Python 3.11. `conda install` raises the following error:

```console
$ conda install nvidia-apex
...
InvalidVersionSpec: Invalid version '*=cuda': invalid character(s)
```

### Configuration

Tested on Ubuntu 18.04 on a private network using a conda-forge mirror.

```console
$ conda info
     active environment : test_nvidia
    active env location : ***/mambaforge/envs/test_nvidia
            shell level : 2
       user config file : ***/.condarc
 populated config files : ***/.condarc
          conda version : 22.11.1
    conda-build version : 3.23.3
         python version : 3.10.6.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.27=0
                          __linux=4.15.0=0
                          __unix=0=0
       base environment : ***/mambaforge  (writable)
      conda av data dir : ***/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://***/artifactory/api/conda/gw_conda.anaconda.org_conda-forge/linux-64
                          https://***/artifactory/api/conda/gw_conda.anaconda.org_conda-forge/noarch
                          https://***/artifactory/api/conda/team-conda/linux-64
                          https://***/artifactory/api/conda/team-conda/noarch
          package cache : ***/mambaforge/pkgs
                          ***/.conda/pkgs
       envs directories : ***/mambaforge/envs
                          ***/.conda/envs
               platform : linux-64
             user-agent : conda/22.11.1 requests/2.28.2 CPython/3.10.6 Linux/4.15.0-202-generic ubuntu/18.04.6 glibc/2.27
                UID:GID : 505:102
             netrc file : None
           offline mode : False
```

### Initialization

```console
$ conda create -n test_nvidia
$ conda activate test_nvidia
$ conda install -y python=3.11
```

### Issue

```console
(test_nvidia) $ conda install nvidia-apex
Collecting package metadata (current_repodata.json): / WARNING conda.core.index:push_record(251): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda102py310hce0d3a8_0 due to InvalidSpec: *=cuda
| WARNING conda.core.index:push_record(251): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda102py38h73d78a8_0 due to InvalidSpec: *=cuda
- WARNING conda.core.index:push_record(251): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda102py39h4af2978_0 due to InvalidSpec: *=cuda
\ WARNING conda.core.index:push_record(251): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda110py310h7cf977e_0 due to InvalidSpec: *=cuda
\ WARNING conda.core.index:push_record(251): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda110py38hf5749dc_0 due to InvalidSpec: *=cuda
| WARNING conda.core.index:push_record(251): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda110py39h31ddb46_0 due to InvalidSpec: *=cuda
\ WARNING conda.core.index:push_record(251): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda111py310h11f0b9a_0 due to InvalidSpec: *=cuda
\ WARNING conda.core.index:push_record(251): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda111py38h7ba73a8_0 due to InvalidSpec: *=cuda
- WARNING conda.core.index:push_record(251): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda111py39h2dd2c40_0 due to InvalidSpec: *=cuda
/ WARNING conda.core.index:push_record(251): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py310h6ec7b7f_0 due to InvalidSpec: *=cuda
- WARNING conda.core.index:push_record(251): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py310hb11405b_1 due to InvalidSpec: *=cuda
\ WARNING conda.core.index:push_record(251): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py311h6c9afd8_1 due to InvalidSpec: *=cuda
/ WARNING conda.core.index:push_record(251): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py38hd717573_1 due to InvalidSpec: *=cuda
/ WARNING conda.core.index:push_record(251): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py38hdf64721_0 due to InvalidSpec: *=cuda
\ WARNING conda.core.index:push_record(251): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py39h83a068c_0 due to InvalidSpec: *=cuda
| WARNING conda.core.index:push_record(251): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py39h955c134_1 due to InvalidSpec: *=cuda
-|/\done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

InvalidVersionSpec: Invalid version '*=cuda': invalid character(s)
```

**Comment by h-vetinari** [comment]
Have you tried with any other python version? It definitely worked in our CI. I also notice that your channels are behind a proxy, perhaps some packages are not up to date or not getting through?

**Comment by rphel** [comment]
It works with:
- Python 3.10 using `conda install` and `mamba install`
- Python 3.11 using `mamba install`

As the install process is successfull on my private network using `mamba` on Python 3.11, it seems there is an issue with `conda` + Python 3.11. 

I see your CI uses `mamba` and `boa` and not a vanilla `conda` install: is it possible that it works because you use mamba?

Thank you for your support!

**Comment by rphel** [comment]
I have no available environment with a direct access to the Internet... so I unable to test.
Still, I found someone else with the same issue as mine: https://github.com/NVIDIA/apex/issues/1561

**Comment by sergsb** [comment]
I have the same problem trying to create a conda package. conda build fails; however, the package I am trying to build does not have any connection with cuda at all! 
[meta.yaml.txt](https://github.com/conda-forge/nvidia-apex-feedstock/files/10699809/meta.yaml.txt)

`
conda build molcomplib -c conda-forge`

```
  File "/home/sergeyadmin/miniconda3/lib/python3.9/site-packages/conda/models/version.py", line 173, in __init__
    raise InvalidVersionSpec(vstr, "invalid character(s)")
conda.exceptions.InvalidVersionSpec: Invalid version '*=cuda': invalid character(s)
```

**Comment by rphel** [comment]
My package doesn't depend directly on `nvidia-apex` either, but as for you it depends on `numpy`!
I think there probably is an obscure relashionship between `numpy` and `nvidia-apex`, causing the dependency graph to consider this package. Weird this issue is only reprodictable on Python 3.11 though.

**Comment by jakirkham** [comment]
Do your channel mirrors include [the conda-forge patched repodata]( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock )? If not, that could be an issue

**Comment by jakirkham** [comment]
Also not sure what the `team-conda` channel listed there is. Though the channel mixing/ordering could be an issue

https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge

**Comment by rphel** [comment]
OK.
I've installed a linux virtual machine (Manjaro) on my personal computer that is **connected directly to the internet**, then installed mamba and executed the steps in my first post: **same result as in my work environment**.

So forget all about private repositories or anything related to mirrors: **this package doesn't work with conda, Python 3.11 on linux**.

You have the steps to reproduce in this issue, so please test on your side if you don't trust me or @sergsb. It's is pretty straighforward.

**Comment by jakirkham** [comment]
Could you please share the steps run on the virtual machine from the start?

**Comment by rphel** [comment]
1. Go to https://github.com/conda-forge/miniforge#mambaforge and download the install script (Linux x86_64 (amd64))
2. In a terminal, go in the download directory and execute the installer `sh Mambaforge-Linux-x86_64.sh`
3. Accept license conditions, let the default install folder and at the end let the installer execute `conda init`.
4. After all operations are done, close this terminal
5. Open a new terminal, check `conda` command if available
6. Execute the following commands:

```console
$ conda create -n test_nvidia  python=3.11
$ conda activate test_nvidia
$ conda install -y nvidia-apex
```

**Comment by lavaux** [comment]
The above procedure causes an InvalidSpec error as well for python 3.10, conda 23.1.0 (fresh miniconda3 install):
```
conda create -n test_nvidia python=3.10
conda activate test_nvidia
conda install nvidia-apex
```
Result:
```
Collecting package metadata (current_repodata.json): - WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda102py310hce0d3a8_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda102py38h73d78a8_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda102py39h4af2978_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda110py310h7cf977e_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda110py38hf5749dc_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda110py39h31ddb46_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda111py310h11f0b9a_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda111py38h7ba73a8_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda111py39h2dd2c40_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py310h6ec7b7f_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py310hb11405b_1 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py311h6c9afd8_1 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py38hd717573_1 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py38hdf64721_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py39h83a068c_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py39h955c134_1 due to InvalidSpec: *=cuda
done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

InvalidVersionSpec: Invalid version '*=cuda': invalid character(s)
```

This broke my continuous integration setup.

**Comment by h-vetinari** [comment]
@jaimergp 

Since you were working on the regex spec matching stuff I though you might have some insight here. `nvidia-apex-proc` has a buildstring that's [literally](https://anaconda.org/conda-forge/nvidia-apex-proc/files) just "cuda", but matching on that seems to fail for various people.

**Comment by jaimergp** [comment]
Wow o.o

It sounds like a bug with conda itself.

I can reproduce with just this:

```
$ CONDA_SUBDIR=linux-64 conda create -n unused --dry-run 'nvidia-apex' --solver=classic
Collecting package metadata (current_repodata.json): / WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda102py310hce0d3a8_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda102py38h73d78a8_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda102py39h4af2978_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda110py310h7cf977e_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda110py38hf5749dc_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda110py39h31ddb46_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda111py310h11f0b9a_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda111py38h7ba73a8_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda111py39h2dd2c40_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py310h6ec7b7f_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py310hb11405b_1 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py311h6c9afd8_1 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py38hd717573_1 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py38hdf64721_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py39h83a068c_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py39h955c134_1 due to InvalidSpec: *=cuda
done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.

InvalidVersionSpec: Invalid version '*=cuda': invalid character(s)
```

**Comment by jaimergp** [comment]
That said, I don't usually see `=` signs in the meta.yaml dependencies.

I would turn

```yaml
      run_constrained:
        # old constraint used "gpu"
        - nvidia-apex-proc =*=cuda|=*=gpu  # [cuda_compiler_version != "None"]
        - nvidia-apex-proc =*=cpu          # [cuda_compiler_version != "None"]
        - pytorch =*={{ proc_type }}*
```

into

```yaml
      run_constrained:
        # old constraint used "gpu"
        - nvidia-apex-proc * cuda  # [cuda_compiler_version != "None"]
        # - nvidia-apex-proc * gpu  # [cuda_compiler_version != "None"]
        # this one below was using != instead of == ? oversight or intentional?
        - nvidia-apex-proc * cpu   # [cuda_compiler_version == "None"]
        - pytorch * {{ proc_type }}*
```

I don't think you can use `|` in conda-build specs, so either `cuda` or `gpu` but not both :(

**Comment by h-vetinari** [comment]
I'm trying to address this with #30. If it still appears after that we can patch the repodata.

**Comment by h-vetinari** [comment]
Thanks for the insights @jaimergp; not obvious that `|` cannot be used once there's build strings involved. I really _really_ dislike semantically significant whitespace (e.g. difference between `nvidia-apex-proc * cpu` and `nvidia-apex-proc *cpu`), so I'm always using the `=`-variant.

> # this one below was using != instead of == ? oversight or intentional?

Indeed, thanks for the catch!

**Comment by jakirkham** [comment]
Should we raise a conda-build issue?

**Comment by williamLyh** [comment]
I'm have the same issue, cannot install nvidia-apex with conda. Is this fixed in any latest verison?

**Comment by chemiskyy** [comment]
Hello I'm also having the same issue (using python3.10 and conda-build) with my CI Conda-packaging workflow, can be seen here:
https://github.com/3MAH/simcoon/actions/workflows/conda-packaging.yml

**Comment by JanuszL** [comment]
Despite https://github.com/conda-forge/nvidia-apex-feedstock/pull/30 I still see wrong entries in `conda/pkgs/cache`. Am I doing something wrong?

**Comment by lavaux** [comment]
It is also failing for me regularly during conda-build, despite purging my local cache. I suspect the conda-forge repository should be cleaned up manually now.  I see a similar version issue for https://github.com/conda-forge/fairscale-feedstock as well.

How can we raise up the issue ?
```
  File "REDACTED/lib/python3.10/site-packages/conda/models/version.py", line 42, in __call__
    val = cls._cache_[arg] = super().__call__(arg)
  File "REDACTED/lib/python3.10/site-packages/conda/models/version.py", line 173, in __init__
    raise InvalidVersionSpec(vstr, "invalid character(s)")
conda.exceptions.InvalidVersionSpec: Invalid version '*=cuda': invalid character(s)
```

I tracked back the origin of the exception to this entry in my conda-build:
```
MatchSpec: kwargs={'name': 'nvidia-apex-proc', 'version': '=*=cuda|=*', 'build': 'gpu'}
```

**Comment by JanuszL** [comment]
Just created https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/418 to fix this issue, @h-vetinari would you mind checking it out?
